package com.ms.petopia.api.notification.dto;

public enum NotificationType {
    // 1. 행사/장소
    FAIR_APPLICATION_APPROVED,
    FAIR_APPLICATION_REJECTED,
    FAIR_CANCELED,

    // 2. 예약/입장
    RESERVATION_CONFIRMED,
    RESERVATION_CHANGED,
    RESERVATION_CANCELED,
    ENTRY_FAILED,

    // 3. 참가업체/부스
    VENDOR_APPLICATION_APPROVED,
    VENDOR_APPLICATION_REJECTED,
    VENDOR_APPLICATION_CANCEL_APPROVED,
    VENDOR_APPLICATION_CANCEL_REJECTED,

    // 4. 결제/정산
    PAYMENT_COMPLETED,
    REFUND_COMPLETED,
    SETTLEMENT_COMPLETED, // 정산완료

}
