package com.ms.petopia.api.notification.dto;

public enum NotificationType {
    // 1. 행사/장소
    FAIR_APPLICATION_SUBMITTED, // 행사 신청 접수(심사 대기) - SUPER_ADMIN용
    FAIR_APPLICATION_APPROVED,
    FAIR_APPLICATION_REJECTED,
    FAIR_CANCELED,
    FAIR_CANCEL_REQUEST_SUBMITTED, // 행사 취소 신청 접수(심사 대기) - SUPER_ADMIN용
    FAIR_CANCEL_REQUEST_APPROVED,
    FAIR_CANCEL_REQUEST_REJECTED,

    // 2. 예약/입장
    RESERVATION_CONFIRMED,
    RESERVATION_CHANGED,
    RESERVATION_CANCELED,
    ENTRY_FAILED,

    // 3. 참가업체/부스
    VENDOR_APPLICATION_SUBMITTED, // 참가 신청 접수(심사 대기) - EVENT_ADMIN용
    VENDOR_APPLICATION_APPROVED,
    VENDOR_APPLICATION_REJECTED,
    VENDOR_APPLICATION_CANCEL_REQUESTED, // 참가 취소 요청 접수(심사 대기) - EVENT_ADMIN용
    VENDOR_APPLICATION_CANCEL_APPROVED,
    VENDOR_APPLICATION_CANCEL_REJECTED,
    BOOTH_VISIT_CHECKED_IN, // 부스 QR 스캔으로 방문이 기록됨 - 방문객(QR 주인)용

    // 4. 사업자 등록
    BUSINESS_REGISTRATION_SUBMITTED, // 사업자 등록 신청 접수(심사 대기) - SUPER_ADMIN용
    BUSINESS_APPROVED,
    BUSINESS_REJECTED,
    BUSINESS_REVOKED,

    // 5. 결제/정산
    PAYMENT_COMPLETED,
    REFUND_COMPLETED,
    SETTLEMENT_COMPLETED, // 정산완료

}
